# Generated by Django 3.1.1 on 2020-10-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicproject',
            name='songFile',
            field=models.FileField(upload_to='songs/'),
        ),
    ]
