# Generated by Django 3.1.1 on 2020-11-18 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20201021_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicproject',
            name='songFile',
            field=models.FileField(upload_to='songs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
    ]
