# Generated by Django 3.1.1 on 2020-11-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20201118_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicproject',
            name='songFile',
            field=models.FileField(upload_to='songs/'),
        ),
    ]
