# Generated by Django 3.1.1 on 2020-11-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20201118_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicproject',
            name='songFile',
            field=models.FileField(default='songs/moonlight.mp3', upload_to='songs/'),
        ),
    ]
